// Regional wellbeing data
export const wellbeingData = [
  { quarter: "2025_Q1", region: "North East", life_satisfaction: 6.9, worthwhile: 7.4, happiness: 7.0, anxiety: 3.9, wellbeing_index: 4.35 },
  { quarter: "2025_Q1", region: "North West", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 6.9, anxiety: 3.7, wellbeing_index: 4.35 },
  { quarter: "2025_Q1", region: "Yorkshire and The Humber", life_satisfaction: 6.9, worthwhile: 7.0, happiness: 7.1, anxiety: 3.9, wellbeing_index: 4.28 },
  { quarter: "2025_Q1", region: "East Midlands", life_satisfaction: 6.8, worthwhile: 7.2, happiness: 7.0, anxiety: 4.0, wellbeing_index: 4.25 },
  { quarter: "2025_Q1", region: "West Midlands", life_satisfaction: 6.8, worthwhile: 7.1, happiness: 6.9, anxiety: 3.9, wellbeing_index: 4.22 },
  { quarter: "2025_Q1", region: "East of England", life_satisfaction: 7.1, worthwhile: 7.3, happiness: 7.0, anxiety: 3.9, wellbeing_index: 4.38 },
  { quarter: "2025_Q1", region: "London", life_satisfaction: 6.7, worthwhile: 7.3, happiness: 6.9, anxiety: 4.1, wellbeing_index: 4.2 },
  { quarter: "2025_Q1", region: "South East", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 7.0, anxiety: 4.0, wellbeing_index: 4.3 },
  { quarter: "2025_Q1", region: "South West", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 7.0, anxiety: 3.8, wellbeing_index: 4.35 },
  { quarter: "2025_Q2", region: "North East", life_satisfaction: 6.8, worthwhile: 7.3, happiness: 6.9, anxiety: 3.9, wellbeing_index: 4.28 },
  { quarter: "2025_Q2", region: "North West", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 6.9, anxiety: 3.8, wellbeing_index: 4.33 },
  { quarter: "2025_Q2", region: "Yorkshire and The Humber", life_satisfaction: 6.9, worthwhile: 7.1, happiness: 7.0, anxiety: 3.9, wellbeing_index: 4.28 },
  { quarter: "2025_Q2", region: "East Midlands", life_satisfaction: 6.8, worthwhile: 7.2, happiness: 7.0, anxiety: 4.0, wellbeing_index: 4.25 },
  { quarter: "2025_Q2", region: "West Midlands", life_satisfaction: 6.8, worthwhile: 7.1, happiness: 6.9, anxiety: 3.9, wellbeing_index: 4.22 },
  { quarter: "2025_Q2", region: "East of England", life_satisfaction: 7.0, worthwhile: 7.3, happiness: 7.0, anxiety: 3.9, wellbeing_index: 4.35 },
  { quarter: "2025_Q2", region: "London", life_satisfaction: 6.7, worthwhile: 7.3, happiness: 6.9, anxiety: 4.1, wellbeing_index: 4.2 },
  { quarter: "2025_Q2", region: "South East", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 7.0, anxiety: 4.0, wellbeing_index: 4.3 },
  { quarter: "2025_Q2", region: "South West", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 7.0, anxiety: 3.8, wellbeing_index: 4.35 },
  { quarter: "2025_Q3", region: "North East", life_satisfaction: 6.8, worthwhile: 7.3, happiness: 6.9, anxiety: 3.9, wellbeing_index: 4.28 },
  { quarter: "2025_Q3", region: "North West", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 6.9, anxiety: 3.8, wellbeing_index: 4.33 },
  { quarter: "2025_Q3", region: "Yorkshire and The Humber", life_satisfaction: 6.9, worthwhile: 7.1, happiness: 7.0, anxiety: 3.9, wellbeing_index: 4.28 },
  { quarter: "2025_Q3", region: "East Midlands", life_satisfaction: 6.8, worthwhile: 7.2, happiness: 7.0, anxiety: 4.0, wellbeing_index: 4.25 },
  { quarter: "2025_Q3", region: "West Midlands", life_satisfaction: 6.8, worthwhile: 7.1, happiness: 6.9, anxiety: 3.9, wellbeing_index: 4.22 },
  { quarter: "2025_Q3", region: "East of England", life_satisfaction: 7.0, worthwhile: 7.3, happiness: 7.0, anxiety: 3.9, wellbeing_index: 4.35 },
  { quarter: "2025_Q3", region: "London", life_satisfaction: 6.7, worthwhile: 7.3, happiness: 6.9, anxiety: 4.1, wellbeing_index: 4.2 },
  { quarter: "2025_Q3", region: "South East", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 7.0, anxiety: 4.0, wellbeing_index: 4.3 },
  { quarter: "2025_Q3", region: "South West", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 7.0, anxiety: 3.8, wellbeing_index: 4.35 },
  { quarter: "2025_Q4", region: "North East", life_satisfaction: 6.8, worthwhile: 7.3, happiness: 6.9, anxiety: 3.9, wellbeing_index: 4.28 },
  { quarter: "2025_Q4", region: "North West", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 6.9, anxiety: 3.8, wellbeing_index: 4.33 },
  { quarter: "2025_Q4", region: "Yorkshire and The Humber", life_satisfaction: 6.9, worthwhile: 7.1, happiness: 7.0, anxiety: 3.9, wellbeing_index: 4.28 },
  { quarter: "2025_Q4", region: "East Midlands", life_satisfaction: 6.8, worthwhile: 7.2, happiness: 7.0, anxiety: 4.0, wellbeing_index: 4.25 },
  { quarter: "2025_Q4", region: "West Midlands", life_satisfaction: 6.8, worthwhile: 7.1, happiness: 6.9, anxiety: 3.9, wellbeing_index: 4.22 },
  { quarter: "2025_Q4", region: "East of England", life_satisfaction: 7.0, worthwhile: 7.3, happiness: 7.0, anxiety: 3.9, wellbeing_index: 4.35 },
  { quarter: "2025_Q4", region: "London", life_satisfaction: 6.7, worthwhile: 7.3, happiness: 6.9, anxiety: 4.1, wellbeing_index: 4.2 },
  { quarter: "2025_Q4", region: "South East", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 7.0, anxiety: 4.0, wellbeing_index: 4.3 },
  { quarter: "2025_Q4", region: "South West", life_satisfaction: 6.9, worthwhile: 7.3, happiness: 7.0, anxiety: 3.8, wellbeing_index: 4.35 }
];

// Loneliness data
export const lonelinessData = [
  { quarter: "2025_Q1", region: "East Midlands", often: 6, some_time: 21, occasionally: 25, hardly_ever: 26, never: 20, lonely_at_least_occasionally_pct: 52, lonely_often_or_sometimes_pct: 27 },
  { quarter: "2025_Q1", region: "East of England", often: 5, some_time: 18, occasionally: 24, hardly_ever: 30, never: 20, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 23 },
  { quarter: "2025_Q1", region: "London", often: 7, some_time: 22, occasionally: 25, hardly_ever: 29, never: 13, lonely_at_least_occasionally_pct: 54, lonely_often_or_sometimes_pct: 29 },
  { quarter: "2025_Q1", region: "North East", often: 9, some_time: 19, occasionally: 19, hardly_ever: 28, never: 23, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 28 },
  { quarter: "2025_Q1", region: "North West", often: 7, some_time: 19, occasionally: 22, hardly_ever: 30, never: 19, lonely_at_least_occasionally_pct: 48, lonely_often_or_sometimes_pct: 26 },
  { quarter: "2025_Q1", region: "South East", often: 6, some_time: 18, occasionally: 27, hardly_ever: 28, never: 18, lonely_at_least_occasionally_pct: 51, lonely_often_or_sometimes_pct: 24 },
  { quarter: "2025_Q1", region: "South West", often: 7, some_time: 18, occasionally: 22, hardly_ever: 32, never: 18, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 25 },
  { quarter: "2025_Q1", region: "West Midlands", often: 5, some_time: 21, occasionally: 20, hardly_ever: 29, never: 22, lonely_at_least_occasionally_pct: 46, lonely_often_or_sometimes_pct: 26 },
  { quarter: "2025_Q1", region: "Yorkshire and The Humber", often: 9, some_time: 20, occasionally: 27, hardly_ever: 26, never: 17, lonely_at_least_occasionally_pct: 56, lonely_often_or_sometimes_pct: 29 },
  { quarter: "2025_Q2", region: "East Midlands", often: 6, some_time: 21, occasionally: 25, hardly_ever: 26, never: 20, lonely_at_least_occasionally_pct: 52, lonely_often_or_sometimes_pct: 27 },
  { quarter: "2025_Q2", region: "East of England", often: 5, some_time: 18, occasionally: 24, hardly_ever: 30, never: 20, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 23 },
  { quarter: "2025_Q2", region: "London", often: 7, some_time: 22, occasionally: 25, hardly_ever: 29, never: 13, lonely_at_least_occasionally_pct: 54, lonely_often_or_sometimes_pct: 29 },
  { quarter: "2025_Q2", region: "North East", often: 9, some_time: 19, occasionally: 19, hardly_ever: 28, never: 23, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 28 },
  { quarter: "2025_Q2", region: "North West", often: 7, some_time: 19, occasionally: 22, hardly_ever: 30, never: 19, lonely_at_least_occasionally_pct: 48, lonely_often_or_sometimes_pct: 26 },
  { quarter: "2025_Q2", region: "South East", often: 6, some_time: 18, occasionally: 27, hardly_ever: 28, never: 18, lonely_at_least_occasionally_pct: 51, lonely_often_or_sometimes_pct: 24 },
  { quarter: "2025_Q2", region: "South West", often: 7, some_time: 18, occasionally: 22, hardly_ever: 32, never: 18, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 25 },
  { quarter: "2025_Q2", region: "West Midlands", often: 5, some_time: 21, occasionally: 20, hardly_ever: 29, never: 22, lonely_at_least_occasionally_pct: 46, lonely_often_or_sometimes_pct: 26 },
  { quarter: "2025_Q2", region: "Yorkshire and The Humber", often: 9, some_time: 20, occasionally: 27, hardly_ever: 26, never: 17, lonely_at_least_occasionally_pct: 56, lonely_often_or_sometimes_pct: 29 },
  { quarter: "2025_Q3", region: "East Midlands", often: 6, some_time: 21, occasionally: 25, hardly_ever: 26, never: 20, lonely_at_least_occasionally_pct: 52, lonely_often_or_sometimes_pct: 27 },
  { quarter: "2025_Q3", region: "East of England", often: 5, some_time: 18, occasionally: 24, hardly_ever: 30, never: 20, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 23 },
  { quarter: "2025_Q3", region: "London", often: 7, some_time: 22, occasionally: 25, hardly_ever: 29, never: 13, lonely_at_least_occasionally_pct: 54, lonely_often_or_sometimes_pct: 29 },
  { quarter: "2025_Q3", region: "North East", often: 9, some_time: 19, occasionally: 19, hardly_ever: 28, never: 23, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 28 },
  { quarter: "2025_Q3", region: "North West", often: 7, some_time: 19, occasionally: 22, hardly_ever: 30, never: 19, lonely_at_least_occasionally_pct: 48, lonely_often_or_sometimes_pct: 26 },
  { quarter: "2025_Q3", region: "South East", often: 6, some_time: 18, occasionally: 27, hardly_ever: 28, never: 18, lonely_at_least_occasionally_pct: 51, lonely_often_or_sometimes_pct: 24 },
  { quarter: "2025_Q3", region: "South West", often: 7, some_time: 18, occasionally: 22, hardly_ever: 32, never: 18, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 25 },
  { quarter: "2025_Q3", region: "West Midlands", often: 5, some_time: 21, occasionally: 20, hardly_ever: 29, never: 22, lonely_at_least_occasionally_pct: 46, lonely_often_or_sometimes_pct: 26 },
  { quarter: "2025_Q3", region: "Yorkshire and The Humber", often: 9, some_time: 20, occasionally: 27, hardly_ever: 26, never: 17, lonely_at_least_occasionally_pct: 56, lonely_often_or_sometimes_pct: 29 },
  { quarter: "2025_Q4", region: "East Midlands", often: 6, some_time: 21, occasionally: 25, hardly_ever: 26, never: 20, lonely_at_least_occasionally_pct: 52, lonely_often_or_sometimes_pct: 27 },
  { quarter: "2025_Q4", region: "East of England", often: 5, some_time: 18, occasionally: 24, hardly_ever: 30, never: 20, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 23 },
  { quarter: "2025_Q4", region: "London", often: 7, some_time: 22, occasionally: 25, hardly_ever: 29, never: 13, lonely_at_least_occasionally_pct: 54, lonely_often_or_sometimes_pct: 29 },
  { quarter: "2025_Q4", region: "North East", often: 9, some_time: 19, occasionally: 19, hardly_ever: 28, never: 23, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 28 },
  { quarter: "2025_Q4", region: "North West", often: 7, some_time: 19, occasionally: 22, hardly_ever: 30, never: 19, lonely_at_least_occasionally_pct: 48, lonely_often_or_sometimes_pct: 26 },
  { quarter: "2025_Q4", region: "South East", often: 6, some_time: 18, occasionally: 27, hardly_ever: 28, never: 18, lonely_at_least_occasionally_pct: 51, lonely_often_or_sometimes_pct: 24 },
  { quarter: "2025_Q4", region: "South West", often: 7, some_time: 18, occasionally: 22, hardly_ever: 32, never: 18, lonely_at_least_occasionally_pct: 47, lonely_often_or_sometimes_pct: 25 },
  { quarter: "2025_Q4", region: "West Midlands", often: 5, some_time: 21, occasionally: 20, hardly_ever: 29, never: 22, lonely_at_least_occasionally_pct: 46, lonely_often_or_sometimes_pct: 26 },
  { quarter: "2025_Q4", region: "Yorkshire and The Humber", often: 9, some_time: 20, occasionally: 27, hardly_ever: 26, never: 17, lonely_at_least_occasionally_pct: 56, lonely_often_or_sometimes_pct: 29 }
];
